### ISSUE TITLE
Indiscernable Letter: urn:cite:hmt:msA.231r

### ISSUE THREAD

**Issue by cshanley18** [hmteditors/hc-il17#2]
The second to last last word in line 395 is somewhat confusing.

Word: urn:cite:hmt:vaimg.VA231RN-0402@0.459,0.544,0.049,0.0165  

The first three letters are clearly “ἤλπ."  The fourth character poses the problem.  Taken on its own, it looks clearly like some sigmas found elsewhere on the page, like the supralinear sigma found on the last line, among others (urn:cite:hmt:vaimg.VA231RN-0402@0.28,0.6469,0.068,0.0173). For this reason, we have not wrapped the letter in an unclear tag.  In context, however, it would not make sense for a sigma to follow pi.  Most texts correct this to "ελπετο," but we have not found an instance in which the scribe of the replacement folios writes an epsilon in this manner.

**Comment by scnevi17** [comment]
This occurs again on urn:cite:hmt:msA.231v

We believe it may be a ligature for "ετο" but we are still not certain.

**Comment by scnevi17** [comment]
We believe that this style represents "ετο" after all.  We have seen multiple other examples.
